name: ams
description: Academy management system.
version: 1.0.0
repository: https://github.com/choiexe1/ams

scripts:
  test: dart test -r github
  build: dart run build_runner build --delete-conflicting-outputs
  build-watch: dart run build_runner watch --delete-conflicting-outputs

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0
